services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload port
    volumes:
      - .:/app
    working_dir: /app
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload --incremental --force_polling